### ISSUE TITLE
Why create a new repo, then import source, instead of forking and working to make the project better?

### ISSUE THREAD

**Issue by HarryR** [AntoineRondelet/snark-mixer#7]
as titled

**Comment by AntoineRondelet** [comment]
Yeah stupid decision I made when I cloned the repo (instead of cloning my fork) to look at the code locally (off-line). Then I made some changes, comments and so on, and ended up working on this repo only. This is more like a playground... although yes, it would have been a better idea to fork the repo directly rather than citing it in the README

**Comment by HarryR** [comment]
You're making some interesting improvements, would be good to get them integrated back into the main repo, will also give you some oversight from the guy who made it - stuff like this is worth getting double checked to avoid foot-gun moments with crypto code.

IMO this mixer project is the most promising for Ethereum at the moment, and has much wider ranging applications than just mixing if the SNARK proofs were to be generalised to anything existing within a Merkle tree.
